version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/python/Dockerfile
    networks:
      - argentina-inflation-network
    volumes:
      - ./app:/app
      - ./.env:/app/.env
    ports:
      - "${API_PORT}:${API_PORT}"

  selenium:
    image: seleniarm/standalone-chromium:latest
    shm_size: 2gb
    restart: always
    networks:
      - argentina-inflation-network

  psql:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - argentina-inflation-network

  redis:
    image: redis:latest
    networks:
      - argentina-inflation-network

networks:
  argentina-inflation-network:
    driver: bridge
