version: "3"

services:
  python:
    build:
      context: ./
      dockerfile: ./docker/python/Dockerfile
    networks:
      - argentina-inflation-network
    volumes:
      - ./:/app
      - ./.env:/app/.env

  selenium:
    image: seleniarm/standalone-chromium:latest
    shm_size: 2gb
    restart: always
    networks:
      - argentina-inflation-network

  psql:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - argentina-inflation-network

networks:
  argentina-inflation-network:
    driver: bridge
